project:
  type: website

website:
  favicon: static/bsa-favicon.png
  title: "NHSBSA DALL Playbook" 
  navbar:
    title: false
    logo: "static/logo-nhs.svg"
    logo-alt: "NHS logo"
    pinned: true
    background: "#005EB8"
    left:
      - href: index.qmd
        text: Home
      - text: "Guidance"
        menu:
        - href: "guidance/pre-pd/index.qmd"
        - href: "guidance/pd/index.qmd"
        - href: "guidance/analysis/index.qmd"
        - href: "guidance/wrap-up/index.qmd"

    right:
      - about.qmd
      - icon: globe
        href: https://www.nhsbsa.nhs.uk/nhsbsa-statistics-and-data-science
      - icon: github
        href: https://github.com/nhsbsa-data-analytics
      - icon: twitter
        href: https://twitter.com/nhsbsa

format:
  html:
    pagetitle: "NHSBSA DALL Playbook"
    lang: en-GB
    theme: cosmo
    css: styles.css
    mainfont: "Arial"
    page-layout: full
    toc: true
