project:
  type: website
  output-dir: docs

website:
  favicon: static/bsa-favicon.png
  title: "NHSBSA DALL Playbook" 
  navbar:
    title: false
    logo: "static/logo-nhs.svg"
    logo-alt: "NHS logo"
    pinned: true
    background: "#005EB8"
    left:
      - href: index.qmd
        text: Home
      - text: "Guidance"
        menu:
        - href: guidance/01-pre-pd/index.qmd
        - href: guidance/02-pd/index.qmd
        - href: guidance/03-analysis/index.qmd
        - href: guidance/04-wrap-up/index.qmd

    right:
      - about.qmd
      - icon: globe
        href: https://www.nhsbsa.nhs.uk/nhsbsa-statistics-and-data-science
      - icon: github
        href: https://github.com/nhsbsa-data-analytics
      - icon: twitter
        href: https://twitter.com/nhsbsa
  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - section: "Before the problem definition"
        contents:
          - guidance/01-pre-pd/index.qmd
          - guidance/01-pre-pd/pre-pd-steps/01-hypothesis-identified.qmd
          - guidance/01-pre-pd/pre-pd-steps/02-assign-critical-friend.qmd
          - guidance/01-pre-pd/pre-pd-steps/03-get-access-to-data.qmd
          - guidance/01-pre-pd/pre-pd-steps/04-customer-engagement.qmd
          - guidance/01-pre-pd/pre-pd-steps/05-create-update-initiative-resources.qmd
      - section: "Problem definition"
        contents:
          - guidance/02-pd/index.qmd
          - guidance/02-pd/pd-steps/01-writing-problem-definition.qmd
          - guidance/02-pd/pd-steps/02-customer-feedback.qmd
          - guidance/02-pd/pd-steps/03-refine-pd.qmd
          - guidance/02-pd/pd-steps/04-estimate-timescales.qmd
          - guidance/02-pd/pd-steps/05-problem-definition-sign-off.qmd
      - section: "Analysis"
        contents:
          - guidance/03-analysis/index.qmd
          - guidance/03-analysis/analysis-steps/01-data-prep.qmd
          - guidance/03-analysis/analysis-steps/02-analysis-modelling.qmd
          - guidance/03-analysis/analysis-steps/03-reporting-and-visuals.qmd
          - guidance/03-analysis/analysis-steps/04-review.qmd
      - section: "Initiative wrap up"
        contents:
          - guidance/04-wrap-up/index.qmd
          - guidance/04-wrap-up/wrap-up-steps/01-clean-up.qmd
          - guidance/04-wrap-up/wrap-up-steps/02-write-documentation.qmd
          - guidance/04-wrap-up/wrap-up-steps/03-update-wiki.qmd
          - guidance/04-wrap-up/wrap-up-steps/04-public-repository.qmd
          - guidance/04-wrap-up/wrap-up-steps/05-future-work.qmd
          - guidance/04-wrap-up/wrap-up-steps/06-follow-up.qmd

format:
  html:
    pagetitle: "NHSBSA DALL Playbook"
    lang: en-GB
    theme: cosmo
    css: styles.css
    mainfont: "Arial"
    page-layout: full
    toc: true
    
execute:
  freeze: auto
